name: Cross Compile
on: [push, pull_request]
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run Main.java
        run: |
          cd src    # Navigate to the src directory
          javac Main.java
          native-image javaCalc
          ./javaCalc
      
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: JavaCalculator-${{ matrix.os }}
          path: javacalculator*
