name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Main on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run Main.java
        run: |
          echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
          javac Main.java
          native-image Main
          
      
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: main-${{ matrix.os }}
          path: main*
